package ma.supmti.entities;
// Generated 15 mai 2021 à 00:38:39 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ma.supmti.Dao.CommandDao;
import ma.supmti.Dao.ProductDao;

/**
 * Command generated by hbm2java
 */
@Entity
@Table(name = "command", catalog = "hibernate")
public class Command implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String label;
	private Double prix;
	private String date_command;
	

	public Command() {
	}


	public Command(String label, Double prix,String  dateCommand) {
		this.label = label;
		this.prix = prix;
		this.date_command = dateCommand;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "prix")
	public Double getPrix() {
		return this.prix;
	}

	public void setPrix(Double prix) {
		this.prix = prix;
	}

	@Column(name = "date_command")
	public String  getDate_command() {
		return this.date_command;
	}

	public void setDate_command(String  dateCommand) {
		this.date_command = dateCommand;
	}

	public List<Command> allCommands() {
		CommandDao dao = new CommandDao();
			return dao.findAllCommands();
	}
	public String getCommandDetailsById(int id_Command) {
        System.out.println("Calling getStudentDetailsById() Method Details For Student Id?= " + id_Command);
        CommandDao ph = new CommandDao();      
        List<Command> CommandList = ph.getCommandById(id_Command);
        for(Command selectedStud : CommandList) {
            label = selectedStud.getLabel();
            prix = selectedStud.getPrix();
            id = selectedStud.getId();
        }
        this.setId(id);
        System.out.println("Fetched Id? " + id + " Details Are: Name=" + label + ", Department=" + prix);
        return "edit";
    }

public String update() {
	System.out.println("Calling updateCommandDetails() Method To Update Command Record");
	CommandDao dao = new CommandDao();
	  dao.updateCommand(this);
	  return "success";
}
public void delete(int id ) {
	System.out.println("Calling delete  Method To delete Command Record");
	CommandDao dao = new CommandDao();
	  dao.deleteCommand(id);
}
	 public void saveCommandRecord() {
	        System.out.println("Calling saveCommandRecord() Method To Save Command Record");
	        CommandDao c= new CommandDao();
	        c.addCommand(this);
	    }

}
