package ma.supmti.entities;
// Generated 23 mai 2021 à 19:20:38 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.transaction.Transactional;

import ma.supmti.Dao.ProductDao;


/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "hibernate")
public class Product implements java.io.Serializable {
	

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
    @Column(name = "id")
	@GeneratedValue(strategy = IDENTITY)
	private Integer id;
	 @Column(name = "label", unique = true, nullable = false, length = 100)
	private String label;
	 @Column(name = "prix")
	private int prix;
	 @Column(name = "categorie")
	 private String categorie ;
	 
	
	

	public String  getCategorie() {
		return categorie;
	}
	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	public int getPrix() {
		return prix;
	}
	public void setPrix(int prix) {
		this.prix = prix;
	}
	
	public Product() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Product( String label, int prix, String categorie) {
		
		this.label = label;
		this.prix = prix;
		this.categorie = categorie;
	}
	public List<Product> getProducts() {
			 ProductDao dao = new ProductDao();
				return dao.findAllProducts();
		}
	
	public String getProductDetailsById(int id_pro) {
        System.out.println("Calling getProductDetailsById() Method Details For Product Id?= " + id_pro);
        ProductDao ph = new ProductDao();       
        List<Product> productsList = ph.getProductById(id_pro);
        for(Product selectedStud : productsList) {
            label = selectedStud.getLabel();
            prix = selectedStud.getPrix();
            id = selectedStud.getId();
        }
        this.setId(id);
        System.out.println("Fetched Id? " + id + " Details Are: Name=" + label + ", prix=" + prix);
        return "edit";
    }

	public String update() {
		System.out.println("Calling updateProductDetails() Method To Update Product Record");
		ProductDao dao = new ProductDao();
		  dao.updateProductRecord(this);
		  return "success";
	}
	public void delete(int id ) {
		System.out.println("Calling delete  Method To delete Product Record");
		ProductDao dao = new ProductDao();
		  dao.deleteProduct(id);
	}

	public void saveProductRecord() {
        System.out.println("Calling saveProductRecord() Method To Save Product Record");
        ProductDao c = new ProductDao();
        c.addProduct(this);
    }

 


	@Override
	  public String toString() {
	    return this.id + " : " + this.label + " " + this.prix;
	  }



}