package ma.supmti.entities;
// Generated Jun 1, 2021, 4:30:30 PM by Hibernate Tools 5.4.30.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private String username;

	public Admin() {
	}

	public Admin(String email, String password, String username) {
		this.email = email;
		this.password = password;
		this.username = username;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
